from .SkipgramTrainerModule import SkipgramTrainerModule
from .SkipgramTrainerModule import DualSkipgramTrainerModule
from .SkipgramTrainerModule import VocabFreeSkipgramTrainerModule

from .CbowTrainerModule import CbowTrainerModule

from .FastTextTrainerModule import FastTextTrainerModule

from .TeacherStudentTrainerModule import TeacherStudentTrainerModule
from .TeacherStudentTrainerModule import StudentTrainerModule
from .TeacherStudentTrainerModule import StudentWithNegativeSamplesTrainerModule

from .VectorSimilarityTrainerModule import VectorCosineSimilarityTrainerModule