from .SentenceClassification import BinarySentenceClassificationTrainerModule
from .SentenceClassification import MulticlassSentenceClassificationTrainerModule
from .SentenceClassification import MultilabelSentenceClassificationTrainerModule

from .WordEmbedding import SkipgramTrainerModule
from .WordEmbedding import DualSkipgramTrainerModule
from .WordEmbedding import CbowTrainerModule
from .WordEmbedding import FastTextTrainerModule
from .WordEmbedding import TeacherStudentTrainerModule
from .WordEmbedding import VectorCosineSimilarityTrainerModule