from .SkipgramTrainerModule import SkipgramTrainerModule
from .SkipgramTrainerModule import DualSkipgramTrainerModule

from .CbowTrainerModule import CbowTrainerModule

from .FastTextTrainerModule import FastTextTrainerModule

from .TeacherStudentTrainerModule import TeacherStudentTrainerModule
from .TeacherStudentTrainerModule import StudentTrainerModule

from .VectorSimilarityTrainerModule import VectorCosineSimilarityTrainerModule