from .SkipgramTrainerModule import SkipgramTrainerModule, DualSkipgramTrainerModule
from .CbowTrainerModule import CbowTrainerModule
from .FastTextTrainerModule import FastTextTrainerModule
from .TeacherStudentTrainerModule import TeacherStudentTrainerModule